<?php

function tablas () {
	return [
			['milestones', 'milestones'],
			['base', 'int'],
			['base_usd','float'],
			['base_usd_of','float'],
			['reservas','int'],
			['base_div_res','float'],
			['usd','float'],
			['usd_of','float'],
			['usd_of_minorista','float'],
			['var_usd_vs_usd_of','float'],
			['circulacion_monetaria','int'],
			['billetes_y_monedas','int'],
			['efectivo_en_ent_fin','int'],
			['depositos_cuenta_ent_fin','int'],
			['depositos','int'],
			['cuentas_corrientes','int'],
			['cajas_ahorro','int'],
			['plazo_fijo','int'],
			['tasa_depositos_30_dias','float'],
			['prestamos','int'],
			['tasa_prestamos_personales','float'],
			['tasa_adelantos_cuenta_corriente','float'],
			['porc_prestamos_vs_depositos','float'],
			['lebac','int'],
			['leliq','int'],
			['lebac_usd','float'],
			['leliq_usd','float'],
			['leliq_usd_of','float'],
			['tasa_leliq','float'],
			['m2_privado_variacion_mensual','float'],
			['cer','float'],
			['uva','float'],
			['uvi','float'],
			['tasa_badlar','float'],
			['tasa_baibar','float'],
			['tasa_tm20','float'],
			['tasa_pase_activas_1_dia','float'],
			['tasa_pase_pasivas_1_dia','float'],
			['inflacion_mensual_oficial','float'],
			['inflacion_interanual_oficial','float'],
			['inflacion_esperada_oficial','float'],
			['dif_inflacion_esperada_vs_interanual','float'],
			['var_base_monetaria_interanual','float'],
			['var_usd_interanual','float'],
			['var_usd_oficial_interanual','float'],
			['var_merval_interanual','float'],
			['var_usd_anual','float'],
			['var_usd_of_anual','float'],
			['var_merval_anual','float'],
			['merval','float'],
			['merval_usd','float']
		];
}